# Dockerfile.server
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY build/libs/ilsem2425dockerexercise-solution-1.0-SNAPSHOT.jar task-manager-server.jar
ENTRYPOINT ["java", "-jar", "task-manager-server.jar"]
