services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-springboot
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskmanager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
      - seeder

  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  seeder:
    build:
      context: .
      dockerfile: Dockerfile-seeder
    depends_on:
      - db

volumes:
  db-data:
