FROM python:3.10-slim
# Set the working directory inside the container
WORKDIR /seeder
# Copy the seeder script to the container
COPY seed.py .
# Install psycopg2-binary for PostgreSQL interaction
RUN pip install --no-cache-dir psycopg2-binary
# Run the seeder script when the container starts
CMD ["python3", "seed.py"]

